### ISSUE TITLE
`group_id` in romancal

### ISSUE THREAD

**Issue by braingram** [spacetelescope/romancal#1259] opened 2024-05-31 19:15 UTC
For some operations (tweakreg, skymatch, resample) models are grouped based on a `group_id`.

This is currently defined in `ModelContainer.models_grouped`:
https://github.com/spacetelescope/romancal/blob/ed6187ffa790fc6a37dd96f7365ba1ef8261fa74/romancal/datamodels/container.py#L498-L504
which assigns a computed value to `model.meta.group_id`

`models_grouped` is used in:
- resample [many_to_many](https://github.com/spacetelescope/romancal/blob/ed6187ffa790fc6a37dd96f7365ba1ef8261fa74/romancal/resample/resample.py#L206) and [many_to_one](https://github.com/spacetelescope/romancal/blob/ed6187ffa790fc6a37dd96f7365ba1ef8261fa74/romancal/resample/resample.py#L286) and [update_exposure_times](https://github.com/spacetelescope/romancal/blob/ed6187ffa790fc6a37dd96f7365ba1ef8261fa74/romancal/resample/resample.py#L517) (some of which is used in outlier detection)
- [skymatch](https://github.com/spacetelescope/romancal/blob/ed6187ffa790fc6a37dd96f7365ba1ef8261fa74/romancal/skymatch/skymatch_step.py#L75)
- [tweakreg](https://github.com/spacetelescope/romancal/blob/ed6187ffa790fc6a37dd96f7365ba1ef8261fa74/romancal/tweakreg/tweakreg_step.py#L267)

Currently group id is always defined in `models_grouped` ignoring any `group_id` in the model metadata (and ignoring any `group_id` in the association, which is used for [jwst](https://github.com/spacetelescope/jwst/blob/743160a1da5a82250deef89f4a93ac5cb1ea1ae7/jwst/datamodels/container.py#L136-L146)).

Most of the above steps are part of the [mosaic](https://github.com/spacetelescope/romancal/blob/ed6187ffa790fc6a37dd96f7365ba1ef8261fa74/romancal/pipeline/mosaic_pipeline.py) pipeline with the only exception being tweakreg which is part of the [exposure](https://github.com/spacetelescope/romancal/blob/ed6187ffa790fc6a37dd96f7365ba1ef8261fa74/romancal/pipeline/exposure_pipeline.py#L27) level pipeline.

There is no test for the exposure level pipeline that doesn't skip tweakreg so it is difficult to guess what should be done here.

For the mosaic pipeline it is possible the mosaic will contain models from different groups which will result in:
- outlier detection using the median across groups to detect outlier (however [in practice](https://github.com/spacetelescope/romancal/pull/1146#issuecomment-2118131737) this isn't occurring as outlier detection it taking a median with a N=1)
- skymatch can group models with the same group id into [SkyGroup](https://github.com/spacetelescope/romancal/blob/ed6187ffa790fc6a37dd96f7365ba1ef8261fa74/romancal/skymatch/skyimage.py#L782) instances (which have their sky adjusted together). However this appears to be partially supported where skygroups are [never created](https://github.com/spacetelescope/romancal/blob/ed6187ffa790fc6a37dd96f7365ba1ef8261fa74/romancal/skymatch/skymatch_step.py#L168) and instead the sky for each model is adjusted separately
- resample will call [many_to_one](https://github.com/spacetelescope/romancal/blob/ed6187ffa790fc6a37dd96f7365ba1ef8261fa74/romancal/resample/resample.py#L277) (it appears the [single](https://github.com/spacetelescope/romancal/blob/ed6187ffa790fc6a37dd96f7365ba1ef8261fa74/romancal/resample/resample_step.py#L60) argument is not passed to `ResampleData` so this is likely always the case). During `many_to_one` each model is drizzled separately however the grouping is used for getting the [number of pointings](https://github.com/spacetelescope/romancal/blob/ed6187ffa790fc6a37dd96f7365ba1ef8261fa74/romancal/resample/resample.py#L286) and for [updating the exposure times](https://github.com/spacetelescope/romancal/blob/ed6187ffa790fc6a37dd96f7365ba1ef8261fa74/romancal/resample/resample.py#L517).

Some questions I have:
- Should outlier detection be using many to many and using the groups?
- Should skymatch be adjusting the sky of models from the same group together (like is done for jwst)?
- Should resample be using the groupings to determine the exposure time and number of pointings?

**Comment by nden** [comment] 2024-05-31 21:12
`group_id` is cheaper to compute from the pool file and add to the association than to compute it when it's needed in the L3 pipeline. All the information needed to compute it should be in the pool file. Adding it will remove a lot of opening and closing of files in the Level 3 pipeline.
The fact that its use hasn't been formalized is a problem in both pipelines. JWST is moving towards formalizing its use and an example jwst association is here

https://github.com/spacetelescope/jwst/blob/master/jwst/datamodels/container.py#L102-L129

Is there a reason not to take advantage of this?

**Comment by nden** [comment] 2024-05-31 21:12
@stscijgbot-rstdms

**Comment by stscijgbot-rstdms** [comment] 2024-05-31 21:16
_This issue is tracked on JIRA as [RCAL-852](https://jira.stsci.edu/browse/RCAL-852)._

**Comment by schlafly** [comment] 2024-06-01 00:58
Thanks Brett.  Broadly, I suspect that we should use this, with exposures defining the group; it would sound like that would mean adding group_id = L2 file name minus the suffix and the SCA name.

Some more specific comments:
- in outlier detection, I suspect that in terms of the final output this doesn't matter, but practically using the groups will result in denser resampled images contributing to the median filtering (with the caveat, as you say, that the current median filtering isn't right)
- Our goal for the sky matching was to match SCAs and not to match the whole array, so that "sounds right" to me for the moment.  i.e., we wouldn't want to make SkyGroups that merge the whole array together.  But I think I understand you to be saying that if we set these group ids that presently undesirable behavior wouldn't happen automatically.
- For resample, it sounds like the exposure times will be fine either way---since the exposure times for the different SCAs of the same exposure are the same, we don't really care whether those max's and min's are grouped or ungrouped.  The number of pointings would be more natural if we set the groups.

**Comment by braingram** [comment] 2024-06-03 13:10
Thanks! To check that I'm following the discussion so far:
- outlier detection could likely use grouping based on a pattern similar to the L2 [file name](https://roman-pipeline.readthedocs.io/en/latest/roman/data_products/file_naming.html#file-naming-schemes)
- grouping is not needed in skymatch as the skys for SCAs will be matched separately. As it appears the group ids are already being ignored here I think this matches what is currently being done.
- resample might be the other reason (aside from outlier detection) to keep the grouping API in the container (as it's currently used in this step)

Since there are 2 uses for grouping (outlier detection and resample) and the code currently expects the grouping to be done in the container it sound like it makes sense to keep the grouping API on the container. This also has the benefit that if another step wants to used the groupings it's already part of the common code (as it is now with `ModelContainer`).

One additional question is do we want to support having the group id in the association? As @nden mentioned this is much more efficient (currently `models_grouped` will open every model as that's the only way to determine the grouping). Allowing this would also make it easier to make the container part of the common jwst/romancal code (perhaps in stpipe or stcal) as jwst allows setting the group id in the association. Allowing group id to be defined in the association would mean that a user could modify the group id by changing the association (although the user could currently modify the group id by changing the files). I don't see this last point as a negative and given the other benefits do you think it's worth allowing the group id to be defined in the association?

**Comment by braingram** [comment] 2024-06-03 13:30
Looking at the group id calculation the current `ModelContainer` generates a group id that doesn't quite match the l2 filenames (ignoring the SCA name and suffix).

| in l2 filename    | in group id |
| --------------- | ----------- |
| program id        | ✔️               |
| execution plan  | ❌               |
| pass                  | ❌               |
| segment           | ❌               |
| visit number     | ✔️               |
| visit group        | ✔️               |
| sequence id     | ✔️               |
| activity             | ✔️               |
| exposure          | ✔️               |

Looking at the RAD schemas, would using `meta.observation.obs_id` make sense:
https://github.com/spacetelescope/rad/blob/5ccb720777ed90faf13897ef92adf738693d8024/src/rad/resources/schemas/observation-1.0.0.yaml#L9
Is this used and kept up-to-date? If so it looks to be the same as the l2 filename minus the SCA and suffix.

**Comment by schlafly** [comment] 2024-06-03 13:56
> * outlier detection could likely use grouping based on a pattern similar to the L2 [file name](https://roman-pipeline.readthedocs.io/en/latest/roman/data_products/file_naming.html#file-naming-schemes)
> * grouping is not needed in skymatch as the skys for SCAs will be matched separately. As it appears the group ids are already being ignored here I think this matches what is currently being done.
> * resample might be the other reason (aside from outlier detection) to keep the grouping API in the container (as it's currently used in this step)

Yes.  Re sky-matching, we're not intending to fit a single offset per exposure at present, but there is a lot of uncertainty about what level of flexibility the sky matching will end up needing to have.  So if it's very easy to have an option to either group by exposure or do individual SCAs, that would be nice.  But it sounds like we're following our intended baseline.

> One additional question is do we want to support having the group id in the association? As @nden mentioned this is much more efficient (currently `models_grouped` will open every model as that's the only way to determine the grouping). Allowing this would also make it easier to make the container part of the common jwst/romancal code (perhaps in stpipe or stcal) as jwst allows setting the group id in the association. Allowing group id to be defined in the association would mean that a user could modify the group id by changing the association (although the user could currently modify the group id by changing the files). I don't see this last point as a negative and given the other benefits do you think it's worth allowing the group id to be defined in the association?

That's fine; I don't feel strongly here.  The only vague awkwardness about defining it in the file is that I really don't see many cases where we want the group to be something other than an exposure.  So there's a little redundancy, but if that redundancy leads us to match Webb it's probably worth it.

I can confirm that recently all L1 files produced by romanisim started including obs_id, and that it looks to me to include all we need to identify an exposure.  A potential implementation concern is that it would be easy to try to make some fake exposures by copying real exposures and changing the file names, believing that one was generating exposures that would be treated as separate exposures.  But if we fail to update obs_id you could be surprised when they're all part of the same exposure.  Or, relatedly, we keep the same information in the actual file name, in meta.filename, and in obsid, and it can be hard to keep these in sync.  So I might prefer a default group based on the first N characters of the file name.  But I don't feel strongly here.

**Comment by braingram** [comment] 2024-06-03 14:32
Keeping things in sync is definitely a concern. Perhaps this is off topic but it looks like `obs_id` is not used in romancal:
https://github.com/search?q=repo%3Aspacetelescope%2Fromancal+obs_id&type=code
Since this is a combination of other metadata is there a reason it's a separate metadata entry (and not a dynamic property of the datamodel)? The same is true for visit_id and in some sense `meta.filename` could also be dynamic (perhaps a `filename` property of the datamodel). This might help to avoid issues like https://github.com/spacetelescope/romancal/issues/818

**Comment by schlafly** [comment] 2024-06-03 14:45
Right, obs_id is set in romanisim during the creation of the L1 files and then not changed by romancal.  Yes, I would be sympathetic to removing meta.filename, but I'm told stpipe cares about it and so that would be a bigger lift.  I do think there's a use to having an overall exposure id (obs_id presently?) in the downstream archive, etc., so I'm not really militating for getting rid of obs_id.

**Comment by braingram** [comment] 2024-06-03 15:35
Thanks! Good point about stpipe and `meta.filename`. Let's leave any changes to that to a separate issue. It's certainly confusing to me.

**Comment by mairanteodoro** [comment] 2024-10-04 15:12
@braingram I supposed this issue has been resolved by ModelLibrary, correct?

**Comment by braingram** [comment] 2024-10-04 17:42
Thanks! Yeah. I'll close the issue.

**Comment by schlafly** [comment] 2024-10-09 18:48
Part of this closed issue was what Roman wants to do for grouping.  I think conceptually the answer is:
- group by exposure / obs_id for outlier detection, tweakreg, and resample
- group by SCA for sky matching
Did ModelLibrary solve that for us naturally?  Sorry, I forgot about this detail.

**Comment by braingram** [comment] 2024-10-10 17:30
I reopened this as I think what you described doesn't match what's currently used in romancal.

ModelLibrary matched the previous grouping by ModelContainer and now generates a group_id using:
https://github.com/spacetelescope/romancal/blob/1945dad5eb600fe82acb865baf3f1d66da12dd7f/romancal/datamodels/library.py#L79-L81
which is used for all steps that use grouping. The steps that use grouping are:
- tweakreg
- outlier detection
- resample

This doesn't quite match `obs_id` (see https://github.com/spacetelescope/romancal/issues/1259#issuecomment-2145212797).

There is also no grouping in sky match. Is that the same as "group by SCA"?

**Comment by schlafly** [comment] 2024-10-10 19:58
Thank you!  It looks to me like obs_id is more correct; i.e., the current approach will group exposures that have different execution plans, passes, and segments, but the same other keywords.

The way that I think about this, Roman data is a stream of exposures, each of which has 18 SCAs.  If I controlled the Roman file names, they would just be r{EXPID}_wfi{SCA}.asdf, where EXPID just incremented exposure by exposure.  We've chosen a more complicated structure for EXPID that has a lot of different pieces that we have endowed with some meaning, but it's rather artificial and we don't want the grouping to know about it.  I expect library.py should just use obsid.

No grouping in sky match is the same as grouping by SCA, since each WfiImage is one SCA, so no changes there, thanks.

**Comment by braingram** [comment] 2024-10-10 20:24
Switching the grouping to `obs_id` should be a straightforward edit of the above linked group id calculation. There are issues that will pop up with fake data in unit tests since `obs_id` might be a `dummy value` etc. It's also possible that `obs_id` will be equal to some value that isn't the same as the combined metadata that makes up the string. I'm not very worried about that for real files and if romanisim fills in the value for simulated data perhaps there's no benefit to trying to make roman_datamodels compute `obs_id` by combining the values.

I started a draft PR here:
https://github.com/spacetelescope/romancal/pull/1448
and a regression tests run:
https://github.com/spacetelescope/RegressionTests/actions/runs/11281421723

**Closed** 2024-10-23 20:34 UTC
